# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='slug'),
        ),
    ]
