# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 22:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='title')),
                ('slug', models.SlugField(validators=[django.core.validators.RegexValidator('^[-\\w]+$')])),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_open', models.BooleanField(default=True, verbose_name='invitations open')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('starts_at', models.DateTimeField(verbose_name='starts at')),
                ('ends_at', models.DateTimeField(verbose_name='ends at')),
                ('registration_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='registartion ends at')),
                ('location', models.CharField(max_length=400, null=True, verbose_name='location')),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=users.models.generate_code)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'New invitation'), (2, 'Invitation sent'), (3, 'Invitation approved'), (4, 'Invitation maybe'), (5, 'Invitation declined')], default=1, verbose_name='Status')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('attendance', models.IntegerField(blank=True, choices=[(1, 'Attended'), (2, 'Partially attended'), (3, 'Did not attend')], null=True, verbose_name='Attendance')),
            ],
            options={
                'ordering': ['event', 'status', 'created_at'],
            },
        ),
    ]
