# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-19 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20171029_0021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-starts_at',), 'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
    ]
