# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('slug', models.CharField(max_length=100, null=True, unique=True, verbose_name='slug')),
                ('summary_markdown', models.TextField(verbose_name='summary (markdown)')),
                ('summary_html', models.TextField(editable=False, verbose_name='summary (html)')),
                ('link', models.URLField(blank=True, null=True, verbose_name='link')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name': 'project bid',
                'verbose_name_plural': 'project bids',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('scope', models.IntegerField(choices=[(1, 'public'), (2, 'private')], verbose_name='comment view scope')),
                ('content', models.TextField(verbose_name='content')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='is reviewed')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
            ],
            options={
                'verbose_name': 'project comment',
                'verbose_name_plural': 'project comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('score', models.IntegerField(choices=[(-1, 'uninterested'), (0, 'neutral'), (1, 'interested'), (2, 'very interested')])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='projects.Project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
