# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q13e_slug', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', django_extensions.db.fields.json.JSONField(default=dict)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forms_filled', models.IntegerField(db_index=True, default=0)),
                ('last_form_filled', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.IntegerField(choices=[(-1, 'n/a'), (1, 'new (incomplete application)'), (2, 'registered'), (5, 'decided not to participate'), (10, 'under discussion'), (11, 'to reject'), (20, 'invite to interview'), (21, 'invited to interview'), (25, 'did not attend interview'), (30, 'participated in interview'), (40, 'to waiting list'), (41, 'waiting list'), (50, 'to accept'), (51, 'accepted'), (100, 'accepted and approved'), (200, 'accepted and declined'), (201, 'rejected')], default=1, verbose_name='status')),
                ('status_changed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_edited_at', models.DateTimeField(auto_now_add=True, verbose_name='last edited at')),
                ('programming_exp', models.IntegerField(blank=True, choices=[('', 'no answer supplied'), (-1, 'too low'), (0, 'average'), (1, 'high'), (2, 'very high')], default=None, null=True, verbose_name='programming experience')),
                ('webdev_exp', models.IntegerField(blank=True, choices=[('', 'no answer supplied'), (0, 'average'), (1, 'high'), (2, 'very high')], null=True, verbose_name='web development experience')),
                ('activism_level', models.IntegerField(blank=True, choices=[('', 'no answer supplied'), (0, 'average'), (1, 'high'), (2, 'very high')], null=True, verbose_name='involvement in activism')),
                ('availability', models.IntegerField(blank=True, choices=[('', 'no answer supplied'), (-1, 'too low'), (0, 'average'), (1, 'high'), (2, 'very high')], null=True, verbose_name='present and future availability')),
                ('humanism_background', models.IntegerField(blank=True, choices=[('', 'no answer supplied'), (0, 'average'), (1, 'high'), (2, 'very high')], null=True, verbose_name='background in humanism')),
                ('comm_skills', models.IntegerField(blank=True, choices=[('', 'no answer supplied'), (0, 'average'), (1, 'high'), (2, 'very high')], null=True, verbose_name='communication skills')),
                ('overall_impression', models.IntegerField(blank=True, choices=[('', 'no answer supplied'), (-1, 'does not fit'), (0, 'undecided / neutral'), (1, 'fit'), (2, 'highly fits')], help_text='Does the candidate fit the program?', null=True, verbose_name='overall_impression')),
                ('comments', models.TextField(blank=True, help_text='Consider adding a user note instead ', verbose_name='review comments')),
            ],
            options={
                'verbose_name': 'application review',
                'verbose_name_plural': 'application reviews',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(-1, 'n/a'), (1, 'new (incomplete application)'), (2, 'registered'), (5, 'decided not to participate'), (10, 'under discussion'), (11, 'to reject'), (20, 'invite to interview'), (21, 'invited to interview'), (25, 'did not attend interview'), (30, 'participated in interview'), (40, 'to waiting list'), (41, 'waiting list'), (50, 'to accept'), (51, 'accepted'), (100, 'accepted and approved'), (200, 'accepted and declined'), (201, 'rejected')])),
                ('value_changed_at', models.DateTimeField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='student_applications.Application')),
            ],
            options={
                'ordering': ('-value_changed_at',),
            },
        ),
    ]
