# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20170915_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='email_content_html',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='email_content',
            field=models.TextField(blank=True, null=True, verbose_name='email content (markdown)'),
        ),
    ]
